"""
Visualization Utility.

This script aggregates training logs and generates clear plots for the final report.
It focuses on:
1. Training Loss Curves (to show convergence).
2. Confusion Matrices (to show classification accuracy).
3. Sample Predictions (to visually demonstrate Sim-to-Real success).
"""

import matplotlib.pyplot as plt
import pandas as pd
import shutil
from pathlib import Path
import config

def plot_training_results():
    """
    Reads the 'results.csv' generated by YOLO and plots custom Loss/mAP curves.
    """
    results_csv = config.REPORTS_DIR / "runs" / config.RUN_NAME / "results.csv"
    
    if not results_csv.exists():
        print("❌ Training results not found. Skip plotting.")
        return

    # Load data
    df = pd.read_csv(results_csv)
    # Strip whitespace from column names (YOLO formatting issue)
    df.columns = df.columns.str.strip()

    # Create a figure with 2 subplots (Loss & mAP)
    fig, ax = plt.subplots(1, 2, figsize=(15, 6))

    # Plot 1: Losses
    ax[0].plot(df['epoch'], df['train/box_loss'], label='Box Loss', linewidth=2)
    ax[0].plot(df['epoch'], df['train/cls_loss'], label='Cls Loss', linewidth=2)
    ax[0].plot(df['epoch'], df['val/box_loss'], label='Val Box Loss', linestyle='--', alpha=0.7)
    ax[0].set_title('Training & Validation Loss')
    ax[0].set_xlabel('Epochs')
    ax[0].set_ylabel('Loss')
    ax[0].legend()
    ax[0].grid(True, alpha=0.3)

    # Plot 2: mAP
    ax[1].plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@50', color='green', linewidth=2)
    ax[1].plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@50-95', color='orange', linewidth=2)
    ax[1].set_title('Mean Average Precision (mAP)')
    ax[1].set_xlabel('Epochs')
    ax[1].set_ylabel('Score')
    ax[1].legend()
    ax[1].grid(True, alpha=0.3)

    # Save the figure
    output_path = config.REPORTS_DIR / "figures" / "training_analysis.png"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(output_path, dpi=300)
    print(f"📈 Analysis chart saved to: {output_path}")

def copy_important_images():
    """
    Copies essential images generated by YOLO (Confusion Matrix, Batches)
    to the main reports folder for easy access.
    """
    source_dir = config.REPORTS_DIR / "runs" / config.RUN_NAME
    dest_dir = config.REPORTS_DIR / "figures"
    
    # List of files automatically generated by YOLO that are useful
    targets = [
        "confusion_matrix.png",
        "confusion_matrix_normalized.png",
        "val_batch0_labels.jpg",  # Ground truth of validation
        "val_batch0_pred.jpg",    # Predictions on validation
        "PR_curve.png"
    ]

    count = 0
    for file_name in targets:
        src = source_dir / file_name
        if src.exists():
            shutil.copy(src, dest_dir / file_name)
            count += 1
    
    print(f"🖼️  Copied {count} standard plots to {dest_dir}")

if __name__ == "__main__":
    print("🚀 Starting Visualization Pipeline...")
    plot_training_results()
    copy_important_images()
    print("✅ Visualization complete.")